### ISSUE TITLE
Heads-up: Textnote has been packaged for FreeBSD

### ISSUE THREAD

**Issue by 0mp** [dkaslovsky/textnote#3]
Hi there! I would like to let you know that I've recently added textnote to the [FreeBSD Ports Collection](https://www.freebsd.org/cgi/man.cgi?query=ports&sektion=&n=1): https://www.freshports.org/textproc/textnote 

Cheers!

**Comment by dkaslovsky** [comment]
@0mp Thanks for doing this, much appreciated!
